/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/jlcerda01.glb -o src/components/jlcerd01.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model/jlcerda01.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1-0-0-2702_jose_cerda_UPPER_ARCH'].geometry} material={nodes['1-0-0-2702_jose_cerda_UPPER_ARCH'].material} />
    </group>
  )
}

useGLTF.preload('/model/jlcerda01.glb')
